# NeON build file (http://github.com/c4s4/neon)

extends:
- c4s4/build/golang.yml
- c4s4/build/release.yml

properties:
  NAME: 'mdpp'

targets:

  run:
    doc: Run MDPP on sample markdown file
    steps:
    - $: ['go', 'run', 'mdpp.go', 'test.md']
